"""IDE base contracts for split GUI mixins.

Auto-generated by `tools/generate_gui_base.py`.
Do not edit manually; regenerate when mixin methods change.
"""

from __future__ import annotations

from typing import Any, Optional

from PyQt6.QtCore import QPoint, Qt, QProcess
from PyQt6.QtWidgets import QWidget, QComboBox, QPlainTextEdit, QTableWidgetItem, QTableWidget, QToolButton


class BluraySubtitleGuiBase(QWidget):
    """Base class with declared instance attrs and method contracts."""

    __init_gui_base_attrs__: bool = False

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        """Initialize QWidget; optionally inject declared attrs for tooling."""
        super().__init__(*args, **kwargs)
        if not bool(getattr(type(self), "__init_gui_base_attrs__", False)):
            return
        self._auto_output_folder = None
        self._bottom_message_remaining = None
        self._bottom_message_text = None
        self._bottom_message_timer = None
        self._chapter_change_reason = None
        self._chapter_checkbox_states = None
        self._chapter_combo_debounce = None
        self._chapter_combo_force_mode = None
        self._chapter_pending_append_episode = None
        self._chapter_pending_remove_row = None
        self._colorful_opacity = None
        self._current_cancel_event = None
        self._encode_input_mode = None
        self._encode_preset_params = None
        self._encode_setting_updating = None
        self._encode_thread = None
        self._encode_worker = None
        self._exe_button_default_text = None
        self._exe_button_progress_text = None
        self._exe_button_progress_value = None
        self._geometry = None
        self._language_code = None
        self._language_updating = None
        self._last_config_inputs = None
        self._last_configuration_34 = None
        self._merge_thread = None
        self._merge_worker = None
        self._mode_group = None
        self._movie_configuration = None
        self._pending_chapter_combo_index = None
        self._pending_subtitle_folder = None
        self._remux_cmd_refresh_timer = None
        self._remux_thread = None
        self._remux_worker = None
        self._selected_function_id = None
        self._selected_main_mpls_prev = None
        self._sp_index_by_bdmv = None
        self._sp_scan_cancel_event = None
        self._sp_scan_in_progress = None
        self._sp_scan_progress_bar = None
        self._sp_scan_progress_dialog = None
        self._sp_scan_progress_done = None
        self._sp_scan_progress_rows_seen = None
        self._sp_scan_progress_show_timer = None
        self._sp_scan_progress_total = None
        self._sp_scan_thread = None
        self._sp_scan_worker = None
        self._sub_pack_group = None
        self._sub_pack_row = None
        self._subtitle_scan_cancel_event = None
        self._subtitle_scan_debounce = None
        self._subtitle_scan_progress_dialog = None
        self._subtitle_scan_seq = None
        self._subtitle_scan_show_timer = None
        self._subtitle_scan_thread = None
        self._subtitle_scan_worker = None
        self._theme_mode = None
        self._track_selection_config = None
        self._track_convert_config = None
        self._track_language_config = None
        self._updating_sp_table = None
        self._vsedit_edit_sessions = None
        self._vsedit_preview_sessions = None
        self.altered = None
        self.approx_episode_minutes_combo = None
        self.bdmv_folder_path = None
        self.bluray_path_box = None
        self.bottom_message_label = None
        self.checkbox1 = None
        self.encode_box = None
        self.encode_source_bdmv_radio = None
        self.encode_source_remux_radio = None
        self.encode_source_row = None
        self.diy_mode_row = None
        self.diy_mode_label = None
        self.diy_simple_radio = None
        self.diy_advanced_radio = None
        self.episode_length_container = None
        self.episode_mode_row = None
        self.exe_button = None
        self.function_button = None
        self.function_tabbar = None
        self.label1 = None
        self.label1_container = None
        self.label2 = None
        self.label2_container = None
        self.language_combo = None
        self.language_label = None
        self.layout = None
        self.merge_options_row = None
        self.movie_mode_radio = None
        self.opacity_label = None
        self.opacity_slider = None
        self.output_folder_path = None
        self.output_folder_row = None
        self.remux_folder_path = None
        self.remux_path_box = None
        self.select_all_tracks_checkbox = None
        self.select_all_tracks_row = None
        self.series_mode_radio = None
        self.sub_check_state = None
        self.sub_pack_external_radio = None
        self.sub_pack_hard_radio = None
        self.sub_pack_soft_radio = None
        self.subtitle_folder_path = None
        self.subtitle_suffix_combo = None
        self.subtitle_suffix_label = None
        self.subtitle_tables_splitter = None
        self.simple_diy_sub_lang_combo = None
        self.simple_diy_sub_lang_label = None
        self.simple_diy_add_sub_row_btn = None
        self.simple_diy_remove_sub_row_btn = None
        self.simple_diy_extra_sub_rows = None
        self.subtitle_label_row = None
        self._simple_diy_subtitle_config = None
        self.track_scope_row = None
        self.track_scope_main_radio = None
        self.track_scope_all_radio = None
        self.table1 = None
        self.table2 = None
        self.table3 = None
        self.tables_splitter = None
        self.theme_combo = None
        self.theme_label = None
        self.vspipe_mode_combo = None
        self.use_getnative_checkbox = None
        self.x265_mode_combo = None
        self.x265_mode_label = None
        self.x265_params_edit = None
        self.x265_params_label = None
        self.x265_preset_combo = None

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        for _name, _obj in BluraySubtitleGuiBase.__dict__.items():
            if _name in ('__init__', '__init_subclass__'):
                continue
            _fn = None
            if isinstance(_obj, staticmethod):
                _fn = _obj.__func__
            elif isinstance(_obj, classmethod):
                _fn = _obj.__func__
            elif callable(_obj):
                _fn = _obj
            if _fn is not None:
                setattr(_fn, "__gui_base_stub__", True)

    def _add_or_update_table3_mpls_as_sp(self, bdmv_index: int, mpls_path: str):
        """Stub for `_add_or_update_table3_mpls_as_sp`."""
        raise NotImplementedError

    def _add_sp_entries_for_unchecked_segments(self, mpls_path: str, segments: list[tuple[int, int]], bdmv_index: int, chapter_to_m2ts: dict=None):
        """Stub for `_add_sp_entries_for_unchecked_segments`."""
        raise NotImplementedError

    def _adjust_combo_width_to_contents(self, combo: QComboBox, padding: int=44, min_width: int=80, max_width: int=520):
        """Stub for `_adjust_combo_width_to_contents`."""
        raise NotImplementedError

    def _all_track_ids_from_streams(self, streams: list[dict[str, object]]) -> tuple[list[str], list[str]]:
        """Stub for `_all_track_ids_from_streams`."""
        raise NotImplementedError

    def _apply_encode_input_mode_ui(self):
        """Stub for `_apply_encode_input_mode_ui`."""
        raise NotImplementedError

    def _apply_end_combo_min_constraint(self, combo: QComboBox, min_allowed: int):
        """Stub for `_apply_end_combo_min_constraint`."""
        raise NotImplementedError

    def _apply_episode_mode_to_table2(self):
        """Stub for `_apply_episode_mode_to_table2`."""
        raise NotImplementedError

    def _apply_language(self, language_code: str):
        """Stub for `_apply_language`."""
        raise NotImplementedError

    def _apply_main_remux_cmds_to_configuration(self, configuration: dict[int, dict[str, int | str]]):
        """Stub for `_apply_main_remux_cmds_to_configuration`."""
        raise NotImplementedError

    def _apply_select_all_tracks_to_main_and_sp(self):
        """Stub for `_apply_select_all_tracks_to_main_and_sp`."""
        raise NotImplementedError

    def _apply_start_chapter_constraints(self, labels: list[str]):
        """Stub for `_apply_start_chapter_constraints`."""
        raise NotImplementedError

    def _apply_theme(self, mode: str):
        """Stub for `_apply_theme`."""
        raise NotImplementedError

    def _bdmv_index_for_table1_folder_norm(self, folder_norm: str) -> int:
        """Stub for `_bdmv_index_for_table1_folder_norm`."""
        raise NotImplementedError

    def _bdmv_to_first_main_mpls_from_table1(self) -> dict[int, str]:
        """table1 row order -> first selected main mpls (no ext) for that disc; matches bdmv_index column."""
        raise NotImplementedError

    def _begin_delayed_busy(self, label_text: str, minimum_delay_sec: float=2.0) -> dict[str, object]:
        """Stub for `_begin_delayed_busy`."""
        raise NotImplementedError

    def _build_end_chapter_combo(self, rows: int, has_beginning: bool, start_value: int, selected_value: int=0) -> QComboBox:
        """Stub for `_build_end_chapter_combo`."""
        raise NotImplementedError

    def _build_episode_output_name_map(self, configuration: dict[int, dict[str, int | str]]) -> dict[int, str]:
        """Stub for `_build_episode_output_name_map`."""
        raise NotImplementedError

    def _build_main_remux_cmd_template(self, mpls_path: str, bdmv_index: int, root: str, *, name_seq_index: int=0, name_seq_total: int=1) -> str:
        """Stub for `_build_main_remux_cmd_template`."""
        raise NotImplementedError

    def _build_start_chapter_options(self, rows: int, has_beginning: bool) -> list[tuple[int, str]]:
        """Stub for `_build_start_chapter_options`."""
        raise NotImplementedError

    def _chapter_label_text(self, value: int, rows: int, has_beginning: bool, for_end: bool=False) -> str:
        """Stub for `_chapter_label_text`."""
        raise NotImplementedError

    def _chapter_node_data(self, mpls_path_no_ext: str) -> dict[str, object]:
        """Stub for `_chapter_node_data`."""
        raise NotImplementedError

    def _cleanup_info_json_if_needed(self):
        """Stub for `_cleanup_info_json_if_needed`."""
        raise NotImplementedError

    def _closest_endpoint(self, start_idx: int, target_sec: float, rows: int, offsets: dict[int, float], m2ts: dict[int, str], checked: list[bool]) -> int:
        """Stub for `_closest_endpoint`."""
        raise NotImplementedError

    def _codec_name_from_codec_id(self, codec_id: str) -> str:
        """Stub for `_codec_name_from_codec_id`."""
        raise NotImplementedError

    def _collect_config_inputs(self) -> dict[str, object]:
        """Stub for `_collect_config_inputs`."""
        raise NotImplementedError

    def _collect_main_remux_cmd_map_from_table1(self) -> dict[str, str]:
        """Stub for `_collect_main_remux_cmd_map_from_table1`."""
        raise NotImplementedError

    def _create_main_remux_cmd_editor(self, text: str, parent: Optional[QWidget]=None) -> QPlainTextEdit:
        """Stub for `_create_main_remux_cmd_editor`."""
        raise NotImplementedError

    def _create_temp_edit_vpy_from_default(self, video_path: str, subtitle_path: str) -> str:
        """Create a temporary editable copy of default vpy with row-specific a/sub_file values."""
        raise NotImplementedError

    def _create_temp_preview_vpy_from_default(self, video_path: str, subtitle_path: str) -> str:
        """Stub for `_create_temp_preview_vpy_from_default`."""
        raise NotImplementedError

    def _diff_config_inputs(self, prev: dict[str, object], cur: dict[str, object]) -> tuple[str, int]:
        """Stub for `_diff_config_inputs`."""
        raise NotImplementedError

    def _edit_chapters_for_mkv(self, mkv_path: str):
        """Stub for `_edit_chapters_for_mkv`."""
        raise NotImplementedError

    def _edit_vpy_with_default_sync(self, video_path: str, subtitle_path: str):
        """Open editable temp script and sync edits back to default vpy (except a=/sub_file=)."""
        raise NotImplementedError

    def _end_delayed_busy(self, state: Optional[dict[str, object]]):
        """Stub for `_end_delayed_busy`."""
        raise NotImplementedError

    def _ensure_default_track_config_for_main(self, mpls_path: str):
        """Stub for `_ensure_default_track_config_for_main`."""
        raise NotImplementedError

    def _extract_attachment_to_temp_and_open(self, mkv_path: str, attachment_id: str, filename: str):
        """Stub for `_extract_attachment_to_temp_and_open`."""
        raise NotImplementedError

    def _extract_track_to_temp_and_open(self, mkv_path: str, track_id: int, codec_id: str):
        """Stub for `_extract_track_to_temp_and_open`."""
        raise NotImplementedError

    def _filtered_chapter_visible_layout(self, mpls_path: str) -> tuple[list[int], dict[int, str]]:
        """Match ChapterWindow: visible chapter rows and chapter_to_m2ts (1-based keys in filtered order)."""
        raise NotImplementedError

    def _find_table3_insert_row_for_entry(self, bdmv_index: int, mpls_file: str, m2ts_file: str) -> int:
        """Stub for `_find_table3_insert_row_for_entry`."""
        raise NotImplementedError

    def _folder_path_for_bdmv_index_from_table1(self, bdmv_index: int) -> str:
        """Bluray root folder for disc column bdmv_index (1-based, same as table1 row + 1)."""
        raise NotImplementedError

    @staticmethod
    def _folder_set_mains_from_configuration(last_cfg: dict[int, dict[str, int | str]]) -> dict[str, set[str]]:
        """Stub for `_folder_set_mains_from_configuration`."""
        raise NotImplementedError

    @staticmethod
    def _folder_set_mains_from_selected(selected: list[tuple[str, str]]) -> dict[str, set[str]]:
        """Stub for `_folder_set_mains_from_selected`."""
        raise NotImplementedError

    def _folders_with_changed_main_selection(self, selected: list[tuple[str, str]], last_cfg: dict[int, dict[str, int | str]]) -> set[str]:
        """Stub for `_folders_with_changed_main_selection`."""
        raise NotImplementedError

    def _generate_configuration_from_ui_inputs(self) -> dict[int, dict[str, int | str]]:
        """Stub for `_generate_configuration_from_ui_inputs`."""
        raise NotImplementedError

    def _get_approx_episode_duration_seconds(self) -> float:
        """Stub for `_get_approx_episode_duration_seconds`."""
        raise NotImplementedError

    def _get_disc_root_for_bdmv_index(self, bdmv_index: int) -> str:
        """Stub for `_get_disc_root_for_bdmv_index`."""
        raise NotImplementedError

    def _get_episode_output_names_from_table2(self) -> list[str]:
        """Stub for `_get_episode_output_names_from_table2`."""
        raise NotImplementedError

    def _get_episode_subtitle_languages_from_table2(self) -> list[str]:
        """Stub for `_get_episode_subtitle_languages_from_table2`."""
        raise NotImplementedError

    def _get_first_m2ts_for_mpls(self, mpls_path: str) -> str:
        """Stub for `_get_first_m2ts_for_mpls`."""
        raise NotImplementedError

    def _get_first_subtitle_path_for_bdmv_index(self, bdmv_index: int) -> str:
        """Stub for `_get_first_subtitle_path_for_bdmv_index`."""
        raise NotImplementedError

    def _get_main_mpls_path_for_bdmv_index(self, bdmv_index: int) -> str:
        """Stub for `_get_main_mpls_path_for_bdmv_index`."""
        raise NotImplementedError

    def _get_playlist_dir_for_bdmv_index(self, bdmv_index: int) -> str:
        """Stub for `_get_playlist_dir_for_bdmv_index`."""
        raise NotImplementedError

    def _get_remux_source_path_from_table2_row(self, row_index: int) -> str:
        """Stub for `_get_remux_source_path_from_table2_row`."""
        raise NotImplementedError

    def _get_remux_source_path_from_table3_row(self, row_index: int) -> str:
        """Stub for `_get_remux_source_path_from_table3_row`."""
        raise NotImplementedError

    def _get_root_for_bdmv_index(self, bdmv_index: int) -> str:
        """Stub for `_get_root_for_bdmv_index`."""
        raise NotImplementedError

    def _get_selected_main_mpls_paths(self) -> list[str]:
        """Stub for `_get_selected_main_mpls_paths`."""
        raise NotImplementedError

    def _get_stream_dir_for_bdmv_index(self, bdmv_index: int) -> str:
        """Stub for `_get_stream_dir_for_bdmv_index`."""
        raise NotImplementedError

    def _get_subtitle_suffix(self) -> str:
        """Stub for `_get_subtitle_suffix`."""
        raise NotImplementedError

    def _has_subtitle_in_table2(self) -> bool:
        """Stub for `_has_subtitle_in_table2`."""
        raise NotImplementedError

    def _inherit_main_track_config_for_sp_key(self, bdmv_index: int, mpls_file: str, sp_key: str):
        """Stub for `_inherit_main_track_config_for_sp_key`."""
        raise NotImplementedError

    @staticmethod
    def _is_auto_chapter_segment_sp_item(out_item: Optional[QTableWidgetItem]) -> bool:
        """SP rows derived from main-mpls chapter inclusion (checkbox / end_at_chapter tail). Not merged from refresh snapshot."""
        raise NotImplementedError

    def _is_movie_mode(self) -> bool:
        """Stub for `_is_movie_mode`."""
        raise NotImplementedError

    def _is_mpls_currently_main(self, mpls_path: str) -> bool:
        """True if this playlist file is the checked main MPLS for its disc row in table1."""
        raise NotImplementedError

    def _localized_headers_for_keys(self, keys: list[str]) -> list[str]:
        """Stub for `_localized_headers_for_keys`."""
        raise NotImplementedError

    def _max_sp_serial_for_bdmv(self, bdmv_index: int) -> int:
        """Stub for `_max_sp_serial_for_bdmv`."""
        raise NotImplementedError

    def _merge_temp_edit_back_to_default_vpy(self, temp_vpy: str):
        """Write edited temp script back into default vpy, preserving a=/sub_file= lines in default."""
        raise NotImplementedError

    def _merge_volume_part_from_last_cfg(self, part: dict[int, dict[str, int | str]], last_cfg: dict[int, dict[str, int | str]], bdmv_index: int) -> None:
        """Restore end_at_chapter / disc_output_name on regenerated no-sub rows when episode keys match."""
        raise NotImplementedError

    def _mkvextract_ext_from_codec_id(self, codec_id: str) -> str:
        """Stub for `_mkvextract_ext_from_codec_id`."""
        raise NotImplementedError

    def _normalize_default_vpy_runtime_lines(self):
        """Ensure default vpy keeps empty runtime placeholders for a= and sub_file=."""
        raise NotImplementedError

    def _normalize_path_input(self, text: str) -> str:
        """Stub for `_normalize_path_input`."""
        raise NotImplementedError

    def _on_edit_tracks_from_sp_table_clicked(self):
        """Stub for `_on_edit_tracks_from_sp_table_clicked`."""
        raise NotImplementedError

    def _on_end_chapter_combo_changed(self, row: int, labels: list[str]):
        """Stub for `_on_end_chapter_combo_changed`."""
        raise NotImplementedError

    def _on_exe_button_progress_text(self, text: str):
        """Stub for `_on_exe_button_progress_text`."""
        raise NotImplementedError

    def _on_exe_button_progress_value(self, value: int):
        """Stub for `_on_exe_button_progress_value`."""
        raise NotImplementedError

    def _on_language_changed(self):
        """Stub for `_on_language_changed`."""
        raise NotImplementedError

    def _on_opacity_changed(self, value: int):
        """Stub for `_on_opacity_changed`."""
        raise NotImplementedError

    def _on_play_sp_table_row_clicked(self):
        """Stub for `_on_play_sp_table_row_clicked`."""
        raise NotImplementedError

    def _on_select_all_tracks_toggled(self, checked: bool):
        """Stub for `_on_select_all_tracks_toggled`."""
        raise NotImplementedError

    def _on_sp_table_scan_finished(self):
        """Stub for `_on_sp_table_scan_finished`."""
        raise NotImplementedError

    def _on_sp_table_scan_result(self, row: int, disabled: bool, special: str, payload: object):
        """Stub for `_on_sp_table_scan_result`."""
        raise NotImplementedError

    def _on_table3_item_changed(self, item: QTableWidgetItem):
        """Stub for `_on_table3_item_changed`."""
        raise NotImplementedError

    def _on_theme_changed(self):
        """Stub for `_on_theme_changed`."""
        raise NotImplementedError

    @staticmethod
    def _parse_display_time_to_seconds(s: str) -> float:
        """Stub for `_parse_display_time_to_seconds`."""
        raise NotImplementedError

    def _parse_stream_pid(self, raw_id: object) -> Optional[int]:
        """Stub for `_parse_stream_pid`."""
        raise NotImplementedError

    def _pid_lang_from_m2ts_track_info(self, tracks: list[dict[str, object]]) -> dict[int, str]:
        """Stub for `_pid_lang_from_m2ts_track_info`."""
        raise NotImplementedError

    def _pid_lang_from_streams(self, streams: list[dict[str, object]]) -> dict[int, str]:
        """Stub for `_pid_lang_from_streams`."""
        raise NotImplementedError

    def _play_m2ts_path(self, m2ts_path: str):
        """Stub for `_play_m2ts_path`."""
        raise NotImplementedError

    def _play_mpls_path(self, mpls_path: str):
        """Stub for `_play_mpls_path`."""
        raise NotImplementedError

    def _populate_encode_from_remux_folder(self):
        """Stub for `_populate_encode_from_remux_folder`."""
        raise NotImplementedError

    def _populate_encode_sps_from_remux_folder(self, folder: str):
        """Stub for `_populate_encode_sps_from_remux_folder`."""
        raise NotImplementedError

    def _preview_script_for_row(self, vpy_path: str, video_path: str, subtitle_path: str):
        """Stub for `_preview_script_for_row`."""
        raise NotImplementedError

    def _read_m2ts_track_info(self, m2ts_path: str) -> list[dict[str, object]]:
        """Stub for `_read_m2ts_track_info`."""
        raise NotImplementedError

    def _read_media_streams_local(self, media_path: str) -> list[dict[str, object]]:
        """Stub for `_read_media_streams_local`."""
        raise NotImplementedError

    def _read_mkvinfo_attachments(self, mkv_path: str) -> list[dict[str, str]]:
        """Stub for `_read_mkvinfo_attachments`."""
        raise NotImplementedError

    def _read_mkvinfo_tracks(self, mkv_path: str) -> list[dict[str, object]]:
        """Stub for `_read_mkvinfo_tracks`."""
        raise NotImplementedError

    def _read_mkvmerge_attachment_ids(self, mkv_path: str) -> dict[str, str]:
        """Stub for `_read_mkvmerge_attachment_ids`."""
        raise NotImplementedError

    def _read_mkvmerge_attachment_rows(self, mkv_path: str) -> list[dict[str, str]]:
        """Stub for `_read_mkvmerge_attachment_rows`."""
        raise NotImplementedError

    def _rebuild_configuration_for_function_34(self):
        """Stub for `_rebuild_configuration_for_function_34`."""
        raise NotImplementedError

    def _recompute_sp_output_names(self, only_bdmv_index: Optional[int]=None):
        """Stub for `_recompute_sp_output_names`."""
        raise NotImplementedError

    def _refresh_all_table_headers(self):
        """Stub for `_refresh_all_table_headers`."""
        raise NotImplementedError

    def _refresh_function_tabbar_theme(self):
        """Stub for `_refresh_function_tabbar_theme`."""
        raise NotImplementedError

    def _refresh_language_column_defaults(self):
        """Stub for `_refresh_language_column_defaults`."""
        raise NotImplementedError

    def _refresh_language_combo(self):
        """Stub for `_refresh_language_combo`."""
        raise NotImplementedError

    def _refresh_language_dependent_sizes(self):
        """Stub for `_refresh_language_dependent_sizes`."""
        raise NotImplementedError

    def _refresh_movie_subtitle_table2(self, rows: Optional[list[tuple[str, str]]]=None):
        """Stub for `_refresh_movie_subtitle_table2`."""
        raise NotImplementedError

    def _refresh_movie_table2(self):
        """Stub for `_refresh_movie_table2`."""
        raise NotImplementedError

    def _refresh_opacity_controls(self):
        """Stub for `_refresh_opacity_controls`."""
        raise NotImplementedError

    def _refresh_subtitle_suffix_options(self):
        """Stub for `_refresh_subtitle_suffix_options`."""
        raise NotImplementedError

    def _refresh_table1_remux_cmds(self):
        """Stub for `_refresh_table1_remux_cmds`."""
        raise NotImplementedError

    def _refresh_theme_combo(self):
        """Stub for `_refresh_theme_combo`."""
        raise NotImplementedError

    def _refresh_track_selection_config_for_selected_main(self):
        """Stub for `_refresh_track_selection_config_for_selected_main`."""
        raise NotImplementedError

    def _remove_table2_rows_by_bdmv_index(self, bdmv_index: int):
        """Stub for `_remove_table2_rows_by_bdmv_index`."""
        raise NotImplementedError

    def _remove_table3_auto_chapter_sp_rows(self, bdmv_index: int, mpls_basename: str):
        """Stub for `_remove_table3_auto_chapter_sp_rows`."""
        raise NotImplementedError

    def _reset_exe_button(self):
        """Stub for `_reset_exe_button`."""
        raise NotImplementedError

    def _resize_table_columns_for_language(self, table: QTableWidget):
        """Stub for `_resize_table_columns_for_language`."""
        raise NotImplementedError

    def _resolve_bdmv_index_for_main_mpls(self, mpls_path: str, fallback_index: int) -> int:
        """Resolve bdmv_index from latest configuration using selected main mpls path."""
        raise NotImplementedError

    def _resolve_output_name_from_mpls(self, mpls_no_ext: str) -> str:
        """Stub for `_resolve_output_name_from_mpls`."""
        raise NotImplementedError

    def _resolve_remux_output_folder(self, base_folder: str) -> str:
        """Stub for `_resolve_remux_output_folder`."""
        raise NotImplementedError

    def _resolve_table2_row_edit_context(self, row_index: int) -> tuple[str, str]:
        """Return (video_path, subtitle_path) for table2 edit-vpy action."""
        raise NotImplementedError

    def _resolve_table3_row_edit_context(self, row_index: int) -> tuple[str, str]:
        """Return (video_path, subtitle_path) for table3 edit-vpy action."""
        raise NotImplementedError

    def _restore_default_vpy_after_preview(self, mapping: dict[str, tuple[str, str]]):
        """Stub for `_restore_default_vpy_after_preview`."""
        raise NotImplementedError

    def _resync_episode_tables_from_main_mpls_selection(self) -> None:
        """After main MPLS toggles, refresh only affected main-mpls configuration."""
        raise NotImplementedError

    def _run_chapter_combo_update(self):
        """Stub for `_run_chapter_combo_update`."""
        raise NotImplementedError

    def _scroll_table_h_to_right(self, table: QTableWidget):
        """Stub for `_scroll_table_h_to_right`."""
        raise NotImplementedError

    def _select_video_path(self, bdmv_index: int, m2ts_files: list[str]) -> str:
        """Stub for `_select_video_path`."""
        raise NotImplementedError

    def _set_compact_table(self, table: QTableWidget, row_height: int=22, header_height: int=22):
        """Stub for `_set_compact_table`."""
        raise NotImplementedError

    def _set_segment_states_for_range(self, mpls_no_ext: str, start_idx: int, end_idx: int, checked: bool):
        """Stub for `_set_segment_states_for_range`."""
        raise NotImplementedError

    def _set_table2_default_column_order(self):
        """Stub for `_set_table2_default_column_order`."""
        raise NotImplementedError

    def _set_table2_subtitle_column_order(self):
        """Stub for `_set_table2_subtitle_column_order`."""
        raise NotImplementedError

    def _set_table_column_visual_order(self, table: QTableWidget, order: list[int]):
        """Stub for `_set_table_column_visual_order`."""
        raise NotImplementedError

    def _set_table_headers(self, table: QTableWidget, keys: list[str]):
        """Stub for `_set_table_headers`."""
        raise NotImplementedError

    def _show_attachments_dialog(self, mkv_path: str):
        """Stub for `_show_attachments_dialog`."""
        raise NotImplementedError

    def _show_bottom_message(self, text: str, duration_ms: int=10000):
        """Stub for `_show_bottom_message`."""
        raise NotImplementedError

    def _show_error_dialog(self, err_text: str):
        """Stub for `_show_error_dialog`."""
        raise NotImplementedError

    def _show_tracks_dialog(self, title: str, streams: list[dict[str, object]], selected_indexes: Optional[set[str]]=None, pid_lang: Optional[dict[int, str]]=None, source_mkv: Optional[str]=None) -> Optional[set[str]]:
        """Stub for `_show_tracks_dialog`."""
        raise NotImplementedError

    def _snapshot_chapter_segment_sp_entries(self) -> list[dict[str, object]]:
        """Preserve ad-hoc SP rows across refresh; auto chapter-segment rows are re-applied via _sync_chapter_checkbox_sp_rows_all_volumes."""
        raise NotImplementedError

    def _split_m2ts_files(self, text: str) -> list[str]:
        """Stub for `_split_m2ts_files`."""
        raise NotImplementedError

    def _start_sp_table_scan(self):
        """Stub for `_start_sp_table_scan`."""
        raise NotImplementedError

    def _start_subtitle_folder_scan(self):
        """Stub for `_start_subtitle_folder_scan`."""
        raise NotImplementedError

    def _sync_chapter_checkbox_sp_for_mpls(self, mpls_path: str, bdmv_index: int):
        """Stub for `_sync_chapter_checkbox_sp_for_mpls`."""
        raise NotImplementedError

    def _sync_chapter_checkbox_sp_rows_all_volumes(self, configuration: dict[int, dict[str, int | str]]):
        """Stub for `_sync_chapter_checkbox_sp_rows_all_volumes`."""
        raise NotImplementedError

    def _sync_end_chapter_min_constraints(self, labels: list[str]):
        """Stub for `_sync_end_chapter_min_constraints`."""
        raise NotImplementedError

    def _table1_bluray_folder_order(self) -> list[str]:
        """Stub for `_table1_bluray_folder_order`."""
        raise NotImplementedError

    def _table3_get_sp_entry_for_row(self, row: int) -> dict[str, int | str]:
        """Stub for `_table3_get_sp_entry_for_row`."""
        raise NotImplementedError

    def _tick_delayed_busy(self, state: Optional[dict[str, object]], text: Optional[str]=None):
        """Stub for `_tick_delayed_busy`."""
        raise NotImplementedError

    def _translate_widget_texts(self):
        """Stub for `_translate_widget_texts`."""
        raise NotImplementedError

    def _unchecked_segments_from_checkbox_states(self, mpls_path: str) -> tuple[list[tuple[int, int]], dict[int, str]]:
        """Filtered table row indices (same as ChapterWindow.get_unchecked_segments) from _chapter_checkbox_states."""
        raise NotImplementedError

    def _update_default_vpy_paths(self, video_path: str, subtitle_path: str) -> dict[str, tuple[str, str]]:
        """Stub for `_update_default_vpy_paths`."""
        raise NotImplementedError

    def _update_exe_button_progress(self, value: Optional[int]=None, text: Optional[str]=None):
        """Stub for `_update_exe_button_progress`."""
        raise NotImplementedError

    def _update_language_combo_enabled_state(self):
        """Stub for `_update_language_combo_enabled_state`."""
        raise NotImplementedError

    def _update_main_row_play_button(self):
        """Stub for `_update_main_row_play_button`."""
        raise NotImplementedError

    def _update_vpy_paths_in_file(self, vpy_path: str, video_path: str, subtitle_path: str) -> bool:
        """Update a=/sub_file=/TextSub toggle in target vpy file for preview context."""
        raise NotImplementedError

    def _video_frame_count(self, media_path: str) -> int:
        """Stub for `_video_frame_count`."""
        raise NotImplementedError

    def _vpy_raw_string(self, path: str) -> str:
        """Stub for `_vpy_raw_string`."""
        raise NotImplementedError

    def add_chapters(self):
        """Stub for `add_chapters`."""
        raise NotImplementedError

    def closeEvent(self, event):
        """Stub for `closeEvent`."""
        raise NotImplementedError

    def create_language_combo(self, initial: str='chi', parent: Optional[QWidget]=None) -> QComboBox:
        """Stub for `create_language_combo`."""
        raise NotImplementedError

    def create_vpy_path_widget(self, initial_path: Optional[str]=None, parent: Optional[QWidget]=None) -> QWidget:
        """Stub for `create_vpy_path_widget`."""
        raise NotImplementedError

    def delete_default_vpy_file(self):
        """Stub for `delete_default_vpy_file`."""
        raise NotImplementedError

    def edit_subtitle(self, path: str):
        """Stub for `edit_subtitle`."""
        raise NotImplementedError

    def encode_bluray(self):
        """Stub for `encode_bluray`."""
        raise NotImplementedError

    def ensure_default_vpy_file(self):
        """Stub for `ensure_default_vpy_file`."""
        raise NotImplementedError

    def ensure_encode_row_widgets(self, row_index: int):
        """Stub for `ensure_encode_row_widgets`."""
        raise NotImplementedError

    def generate_subtitle(self, silent_mode: bool=False):
        """Stub for `generate_subtitle`."""
        raise NotImplementedError

    def get_default_vpy_path(self) -> str:
        """Stub for `get_default_vpy_path`."""
        raise NotImplementedError

    def get_mkv_files_in_table_order(self):
        """
            Get mkv files from table2 in the order they are displayed (respecting sorting).
            """
        raise NotImplementedError

    def get_selected_function_id(self) -> int:
        """Stub for `get_selected_function_id`."""
        raise NotImplementedError

    def get_selected_mpls_no_ext(self) -> list[tuple[str, str]]:
        """Stub for `get_selected_mpls_no_ext`."""
        raise NotImplementedError

    def get_sp_vpy_path_from_row(self, row_index: int) -> str:
        """Stub for `get_sp_vpy_path_from_row`."""
        raise NotImplementedError

    def get_vpy_path_from_row(self, row_index: int) -> str:
        """Stub for `get_vpy_path_from_row`."""
        raise NotImplementedError

    def init_encode_box(self):
        """Stub for `init_encode_box`."""
        raise NotImplementedError

    def init_ui(self):
        """Stub for `init_ui`."""
        raise NotImplementedError

    def main(self):
        """Stub for `main`."""
        raise NotImplementedError

    def on_bdmv_folder_path_change(self):
        """Stub for `on_bdmv_folder_path_change`."""
        raise NotImplementedError

    def on_button_click(self, mpls_path: str, is_main_at_build: bool=True, bdmv_index: int=0):
        """Stub for `on_button_click`."""
        raise NotImplementedError

    def on_button_main(self, mpls_path: str, clicked_checked: Optional[bool]=None):
        """Stub for `on_button_main`."""
        raise NotImplementedError

    def on_button_play(self, mpls_path: str, btn: QToolButton):
        """Stub for `on_button_play`."""
        raise NotImplementedError

    def on_chapter_combo(self, subtitle_index: int):
        """Stub for `on_chapter_combo`."""
        raise NotImplementedError

    def on_configuration(self, configuration: dict[int, dict[str, int | str]], update_sp_table: bool=True):
        """Stub for `on_configuration`."""
        raise NotImplementedError

    def on_edit_attachments_from_mkv_row(self, table: QTableWidget, row_index: int):
        """Stub for `on_edit_attachments_from_mkv_row`."""
        raise NotImplementedError

    def on_edit_chapters_from_mkv_row(self, table: QTableWidget, row_index: int):
        """Stub for `on_edit_chapters_from_mkv_row`."""
        raise NotImplementedError

    def on_edit_sp_vpy_clicked(self):
        """Stub for `on_edit_sp_vpy_clicked`."""
        raise NotImplementedError

    def on_edit_tracks_from_mkv_row(self, table: QTableWidget, row_index: int):
        """Stub for `on_edit_tracks_from_mkv_row`."""
        raise NotImplementedError

    def on_edit_tracks_from_mpls(self, mpls_path: str):
        """Stub for `on_edit_tracks_from_mpls`."""
        raise NotImplementedError

    def on_edit_tracks_from_sp_table(self, row: int):
        """Stub for `on_edit_tracks_from_sp_table`."""
        raise NotImplementedError

    def on_edit_vpy_clicked(self):
        """Stub for `on_edit_vpy_clicked`."""
        raise NotImplementedError

    def on_play_sp_table_row(self, row_index: int, bdmv_col: int, mpls_col: int, m2ts_col: int):
        """Stub for `on_play_sp_table_row`."""
        raise NotImplementedError

    def on_play_table2_disc_row(self, row_index: int, bdmv_col: int, m2ts_col: int):
        """Stub for `on_play_table2_disc_row`."""
        raise NotImplementedError

    def on_preview_script_clicked(self):
        """Stub for `on_preview_script_clicked`."""
        raise NotImplementedError

    def on_preview_sp_scripts_clicked(self):
        """Stub for `on_preview_sp_scripts_clicked`."""
        raise NotImplementedError

    def on_select_function(self, force: bool=False, keep_inputs: bool=False, keep_state: bool=False):
        """Stub for `on_select_function`."""
        raise NotImplementedError

    def on_subtitle_drop(self):
        """Stub for `on_subtitle_drop`."""
        raise NotImplementedError

    def on_subtitle_folder_path_change(self):
        """Stub for `on_subtitle_folder_path_change`."""
        raise NotImplementedError

    def on_subtitle_menu(self, pos: QPoint):
        """Stub for `on_subtitle_menu`."""
        raise NotImplementedError

    def on_subtitle_select(self):
        """Stub for `on_subtitle_select`."""
        raise NotImplementedError

    def on_subtitle_table_sorted(self, logicalIndex: int, order: Qt.SortOrder):
        """Stub for `on_subtitle_table_sorted`."""
        raise NotImplementedError

    def open_file_path(self, path: str):
        """Stub for `open_file_path`."""
        raise NotImplementedError

    def open_folder_path(self, path: str):
        """Stub for `open_folder_path`."""
        raise NotImplementedError

    def open_vpy_in_editor(self, path: str):
        """Stub for `open_vpy_in_editor`."""
        raise NotImplementedError

    def open_vpy_in_vsedit(self, path: str) -> Optional[QProcess]:
        """Stub for `open_vpy_in_vsedit`."""
        raise NotImplementedError

    def refresh_sp_table(self, configuration: dict[int, dict[str, int | str]]):
        """Stub for `refresh_sp_table`."""
        raise NotImplementedError

    def remux_episodes(self):
        """Stub for `remux_episodes`."""
        raise NotImplementedError

    def select_bdmv_folder(self):
        """Stub for `select_bdmv_folder`."""
        raise NotImplementedError

    def select_output_folder(self):
        """Stub for `select_output_folder`."""
        raise NotImplementedError

    def select_remux_folder(self):
        """Stub for `select_remux_folder`."""
        raise NotImplementedError

    def select_subtitle_folder(self):
        """Stub for `select_subtitle_folder`."""
        raise NotImplementedError

    def set_vpy_hardsub_enabled(self, enabled: bool):
        """Stub for `set_vpy_hardsub_enabled`."""
        raise NotImplementedError

    def t(self, text: str) -> str:
        """Stub for `t`."""
        raise NotImplementedError
