"""Target module for VPy edit/preview methods of `BluraySubtitleGUI`."""
import os
import re
import shutil
import subprocess
import sys
import tempfile
from typing import Optional

from PyQt6.QtCore import QProcess
from PyQt6.QtWidgets import QWidget, QHBoxLayout, QLineEdit, QPushButton, QFileDialog, QMessageBox

from src.core.settings import ENCODE_REMUX_LABELS, ENCODE_LABELS, VSEDIT_PATH, ENCODE_SP_LABELS, \
    ENCODE_REMUX_SP_LABELS
from src.exports.utils import print_exc_terminal
from .gui_base import BluraySubtitleGuiBase


class VpyEditPreviewMixin(BluraySubtitleGuiBase):
    def get_default_vpy_path(self) -> str:
        return os.path.normpath(os.path.abspath('vpy.vpy'))

    def ensure_default_vpy_file(self):
        path = self.get_default_vpy_path()
        if os.path.exists(path) and os.path.isfile(path):
            return
        deband_line = 'dbed = core.neo_f3kdb.Deband(nr16, 12, 72, 48, 48, 0, 0, output_depth=16).neo_f3kdb.Deband(24, 56, 32, 32, 0, 0, output_depth=16)\n'
        if sys.platform != 'win32':
            deband_line = 'dbed = core.placebo.Deband(nr16, planes=7, iterations=2, threshold=4.5, radius=16.0, grain=0.0)\n'
        plugin_line = (
            '' if sys.platform == 'win32' else
            'PLUGIN_PATH = "/app/plugins" if os.path.exists("/.dockerenv") else os.path.expanduser("~/plugins")\n'
            'core.std.LoadAllPlugins(PLUGIN_PATH)\n'
        )
        content = (
                'import os\n'
                'import hashlib\n'
                'import vapoursynth as vs\n'
                'from vapoursynth import core\n'
                'import mvsfunc as mvf\n'
                + plugin_line +
                '\n'
                '\n'
                'GRAY_CF = getattr(vs, "GRAY", None)\n'
                'if GRAY_CF is None:\n'
                '    GRAY_CF = getattr(vs.ColorFamily, "GRAY", 1)\n'
                '    try:\n'
                '        setattr(vs, "GRAY", GRAY_CF)\n'
                '    except Exception:\n'
                '        pass\n'
                'YUV_CF = getattr(vs, "YUV", None)\n'
                'if YUV_CF is None:\n'
                '    YUV_CF = getattr(vs.ColorFamily, "YUV", 2)\n'
                '    try:\n'
                '        setattr(vs, "YUV", YUV_CF)\n'
                '    except Exception:\n'
                '        pass\n'
                'if not hasattr(vs, "INTEGER"):\n'
                '    try:\n'
                '        setattr(vs, "INTEGER", getattr(vs.SampleType, "INTEGER", 0))\n'
                '    except Exception:\n'
                '        pass\n'
                'if not hasattr(vs, "FLOAT"):\n'
                '    try:\n'
                '        setattr(vs, "FLOAT", getattr(vs.SampleType, "FLOAT", 1))\n'
                '    except Exception:\n'
                '        pass\n'
                'a = r""  # optional, auto-generated by app\n'
                'native_h = 0  # optional, auto-generated by app\n'
                'native_kernel = ""  # optional, auto-generated by app\n'
                '\n'
                'try:\n'
                '    src8 = core.lsmas.LWLibavSource(a)\n'
                'except BaseException as _e:\n'
                '    if _e.__class__ in (KeyboardInterrupt, SystemExit):\n'
                '        raise\n'
                '    if type(_e).__name__ in ("KeyboardInterrupt", "SystemExit"):\n'
                '        raise\n'
                '    if hasattr(core, "ffms2"):\n'
                '        _t = os.environ.get("TEMP") or os.environ.get("TMP") or os.path.expandvars("%TEMP%") or "."\n'
                '        _k = hashlib.sha1(os.path.normcase(os.path.normpath(a)).encode("utf-8")).hexdigest()\n'
                '        _ffidx = os.path.join(_t, "bluraysub_ffms2_" + _k + ".ffindex")\n'
                '        try:\n'
                '            src8 = core.ffms2.Source(a, cachefile=_ffidx)\n'
                '        except TypeError:\n'
                '            src8 = core.ffms2.Source(a)\n'
                '    else:\n'
                '        raise\n'
                'src16 = core.fmtc.bitdepth(src8, bits=16)\n'
                'target_w = src16.width\n'
                'target_h = src16.height\n'
                'proc16 = src16\n'
                'proc_w = target_w\n'
                'proc_h = target_h\n'
                'if native_h and native_h > 0 and native_h < target_h:\n'
                '    nh = int(native_h)\n'
                '    if nh % 2:\n'
                '        nh -= 1\n'
                '    native_w = int(round(nh * target_w / target_h))\n'
                '    if native_w % 2:\n'
                '        native_w -= 1\n'
                '    if native_w > 0:\n'
                '        proc_w = native_w\n'
                '        proc_h = nh\n'
                '        kl = (native_kernel or "").lower()\n'
                '        if "lanczos" in kl and hasattr(core.descale, "Delanczos"):\n'
                '            low = core.descale.Delanczos(src16, native_w, nh, taps=3)\n'
                '        elif "bilinear" in kl and hasattr(core.descale, "Debilinear"):\n'
                '            low = core.descale.Debilinear(src16, native_w, nh)\n'
                '        elif hasattr(core.descale, "Debicubic"):\n'
                '            low = core.descale.Debicubic(src16, native_w, nh, b=1/3, c=1/3)\n'
                '        else:\n'
                '            low = core.resize.Bicubic(src16, native_w, nh)\n'
                '        proc16 = low\n'
                'nr16 = core.nlm_ispc.NLMeans(proc16, d=0, wmode=3, h=3)\n'
                + deband_line +
                'dbed = mvf.LimitFilter(dbed, nr16, thr=0.55, elast=1.5, planes=[0, 1, 2])\n'
                'nr16Y = core.std.ShufflePlanes(nr16, 0, GRAY_CF)\n'
                'aa_nr16Y = core.eedi2.EEDI2(nr16Y, field=1, mthresh=10, lthresh=20, vthresh=20, maxd=24, nt=50)\n'
                'aa_nr16Y = core.fmtc.resample(aa_nr16Y, proc_w, proc_h, 0, -0.5).std.Transpose()\n'
                'aa_nr16Y = core.eedi2.EEDI2(aa_nr16Y, field=1, mthresh=10, lthresh=20, vthresh=20, maxd=24, nt=50)\n'
                'aa_nr16Y = core.fmtc.resample(aa_nr16Y, proc_h, proc_w, 0, -0.5).std.Transpose()\n'
                'aaedY = core.rgvs.Repair(aa_nr16Y, nr16Y, 2)\n'
                'dbedY = core.std.ShufflePlanes(dbed, 0, GRAY_CF)\n'
                'mergedY = mvf.LimitFilter(dbedY, aaedY, thr=1.0, elast=1.5)\n'
                'merged = core.std.ShufflePlanes([mergedY, dbed], [0,1,2], YUV_CF)\n'
                'if proc_w != target_w or proc_h != target_h:\n'
                '    merged = core.resize.Spline64(merged, target_w, target_h)\n'
                'res = merged\n'
                'Debug = False\n'
                'if Debug:\n'
                '    res = mvf.ToRGB(res, full=False, depth=8)\n'
                'else:\n'
                '    res = core.fmtc.bitdepth(res, bits=10)\n'
                '# sub_file = ""  # optional, auto-generated by app\n'
                '# res = core.assrender.TextSub(res, file=sub_file)\n'
                'res.set_output()\n'
                'src8.set_output(1)\n'
        )
        try:
            with open(path, 'w', encoding='utf-8') as fp:
                fp.write(content)
        except Exception:
            print_exc_terminal()

    def delete_default_vpy_file(self):
        path = self.get_default_vpy_path()
        try:
            if os.path.exists(path) and os.path.isfile(path):
                os.remove(path)
        except Exception:
            print_exc_terminal()

    def set_vpy_hardsub_enabled(self, enabled: bool):
        path = self.get_default_vpy_path()
        if enabled and not os.path.exists(path):
            self.ensure_default_vpy_file()
        if not os.path.exists(path):
            return

        target_1 = 'sub_file = \"\"  # optional, auto-generated by app'
        target_2 = 'res = core.assrender.TextSub(res, file=sub_file)'

        try:
            with open(path, 'r', encoding='utf-8') as fp:
                lines = fp.readlines()
        except Exception:
            print_exc_terminal()
            return

        updated = False
        new_lines: list[str] = []
        for line in lines:
            raw = line.rstrip('\n')
            stripped = raw.lstrip()
            uncommented = stripped
            if stripped.startswith('#'):
                uncommented = stripped[1:].lstrip()

            if uncommented == target_1 or uncommented == target_2:
                updated = True
                if enabled:
                    new_lines.append(uncommented + '\n')
                else:
                    new_lines.append('# ' + uncommented + '\n')
            else:
                new_lines.append(line)

        if not updated:
            return

        try:
            with open(path, 'w', encoding='utf-8') as fp:
                fp.writelines(new_lines)
        except Exception:
            print_exc_terminal()

    def create_vpy_path_widget(self, initial_path: Optional[str] = None, parent: Optional[QWidget] = None) -> QWidget:
        widget = QWidget(parent or self.table2)
        layout = QHBoxLayout()
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(6)
        widget.setLayout(layout)

        line_edit = QLineEdit(widget)
        line_edit.setText(initial_path or self.get_default_vpy_path())

        button = QPushButton(self.t('Select'), widget)

        def select_file():
            start_dir = os.path.dirname(line_edit.text()) if line_edit.text() else os.getcwd()
            path, _ = QFileDialog.getOpenFileName(
                self,
                self.t("Select VPy File"),
                start_dir,
                "Python/VapourSynth (*.py *.vpy)"
            )
            if path:
                line_edit.setText(os.path.normpath(path))

        button.clicked.connect(select_file)
        layout.addWidget(line_edit)
        layout.addWidget(button)
        return widget

    def get_vpy_path_from_row(self, row_index: int) -> str:
        if self.get_selected_function_id() != 4:
            return ''
        labels = ENCODE_REMUX_LABELS if getattr(self, '_encode_input_mode', 'bdmv') == 'remux' else ENCODE_LABELS
        vpy_col = labels.index('vpy_path')
        w = self.table2.cellWidget(row_index, vpy_col)
        if w:
            line_edit = w.findChild(QLineEdit)
            if line_edit:
                return line_edit.text().strip()
        item = self.table2.item(row_index, vpy_col)
        return item.text().strip() if item else ''

    def open_vpy_in_editor(self, path: str):
        if not path:
            QMessageBox.information(self, "Prompt", "VPy path is empty")
            return
        if not os.path.exists(path):
            QMessageBox.information(self, "Prompt", f"File does not exist: {path}")
            return
        if sys.platform == 'win32':
            os.startfile(path)
        else:
            subprocess.Popen(['xdg-open', path])

    def open_vpy_in_vsedit(self, path: str) -> Optional[QProcess]:
        path = str(path or '').strip()
        if not path:
            QMessageBox.information(self, "Prompt", "VPy path is empty")
            return None
        if not os.path.exists(path):
            QMessageBox.information(self, "Prompt", f"File does not exist: {path}")
            return None

        vsedit_exe = VSEDIT_PATH
        if not vsedit_exe or not os.path.exists(vsedit_exe):
            vsedit_exe = shutil.which('vsedit') or ''
        if not vsedit_exe:
            QMessageBox.information(self, "Prompt", "vsedit not found, check VSEDIT_PATH or system PATH")
            return None

        try:
            proc = QProcess(self)
            proc.setProgram(vsedit_exe)
            proc.setArguments([os.path.normpath(path)])
            proc.start()
            if not proc.waitForStarted(2000):
                QMessageBox.warning(self, "Prompt", "Failed to launch vsedit")
                try:
                    proc.kill()
                except Exception:
                    pass
                proc.deleteLater()
                return None
            return proc
        except Exception as e:
            QMessageBox.warning(self, "Prompt", f"Failed to open vsedit: {e}")
            return None

    def _restore_default_vpy_after_preview(self, mapping: dict[str, tuple[str, str]]):
        try:
            vpy_path = self.get_default_vpy_path()
            if not os.path.exists(vpy_path):
                return
            with open(vpy_path, 'r', encoding='utf-8') as fp:
                lines = fp.readlines()

            def norm(s: str) -> str:
                return s.rstrip('\r\n')

            restore_by_modified = {norm(mod): orig for orig, mod in mapping.values() if
                                   orig is not None and mod is not None}

            changed = False
            for idx, line in enumerate(lines):
                key = norm(line)
                if key in restore_by_modified:
                    lines[idx] = restore_by_modified[key] + '\n'
                    changed = True

            if changed:
                with open(vpy_path, 'w', encoding='utf-8') as fp:
                    fp.writelines(lines)
        except Exception:
            pass

    def _vpy_raw_string(self, path: str) -> str:
        s = str(path or '')
        s = s.replace('\\', '\\\\').replace('"', '\\"')
        return f'r"{s}"'

    def _update_vpy_paths_in_file(self, vpy_path: str, video_path: str, subtitle_path: str) -> bool:
        """Update a=/sub_file=/TextSub toggle in target vpy file for preview context."""
        vpy_path = os.path.normpath(str(vpy_path or '').strip())
        if not vpy_path or not os.path.exists(vpy_path):
            raise FileNotFoundError(vpy_path)

        with open(vpy_path, 'r', encoding='utf-8') as fp:
            lines = fp.readlines()

        def norm(s: str) -> str:
            return s.rstrip('\r\n')

        changed = False
        for idx, line in enumerate(lines):
            raw = norm(line)
            m_a = re.match(r'^(\s*)(#\s*)?(a\s*=\s*)r?[\'"].*?[\'"](\s*(#.*)?)$', raw)
            if m_a:
                indent = m_a.group(1)
                expr = m_a.group(3)
                suffix = m_a.group(4) or ''
                new_raw = f'{indent}{expr}{self._vpy_raw_string(video_path)}{suffix}'
                if new_raw != raw:
                    lines[idx] = new_raw + '\n'
                    changed = True
                continue

            m_s = re.match(r'^(\s*)(#\s*)?(sub_file\s*=\s*)r?[\'"].*?[\'"](\s*(#.*)?)$', raw)
            if m_s:
                indent = m_s.group(1)
                expr = m_s.group(3)
                suffix = m_s.group(4) or ''
                want_commented = not bool(subtitle_path)
                comment_prefix = '# ' if want_commented else ''
                rhs = self._vpy_raw_string(subtitle_path or '')
                new_raw = f'{indent}{comment_prefix}{expr}{rhs}{suffix}'
                if new_raw != raw:
                    lines[idx] = new_raw + '\n'
                    changed = True
                continue

            m_t = re.match(
                r'^(\s*)(#\s*)?(res\s*=\s*core\.assrender\.TextSub\(\s*res\s*,\s*file\s*=\s*sub_file\s*\))(\s*(#.*)?)$',
                raw)
            if m_t:
                indent = m_t.group(1)
                expr = m_t.group(3)
                suffix = m_t.group(4) or ''
                want_commented = not bool(subtitle_path)
                comment_prefix = '# ' if want_commented else ''
                new_raw = f'{indent}{comment_prefix}{expr}{suffix}'
                if new_raw != raw:
                    lines[idx] = new_raw + '\n'
                    changed = True
                continue

        if changed:
            with open(vpy_path, 'w', encoding='utf-8') as fp:
                fp.writelines(lines)
        return changed

    def _update_default_vpy_paths(self, video_path: str, subtitle_path: str) -> dict[str, tuple[str, str]]:
        self.ensure_default_vpy_file()
        vpy_path = self.get_default_vpy_path()
        if not os.path.exists(vpy_path):
            raise FileNotFoundError(vpy_path)

        with open(vpy_path, 'r', encoding='utf-8') as fp:
            lines = fp.readlines()

        def norm(s: str) -> str:
            return s.rstrip('\r\n')

        mapping: dict[str, tuple[str, str]] = {}
        changed = False
        for idx, line in enumerate(lines):
            raw = norm(line)
            m_a = re.match(r'^(\s*)(#\s*)?(a\s*=\s*)r?[\'"].*?[\'"](\s*(#.*)?)$', raw)
            if m_a:
                indent = m_a.group(1)
                expr = m_a.group(3)
                suffix = m_a.group(4) or ''
                new_raw = f'{indent}{expr}{self._vpy_raw_string(video_path)}{suffix}'
                if new_raw != raw:
                    lines[idx] = new_raw + '\n'
                    changed = True
                mapping['a'] = (raw, new_raw)
                continue

            m_s = re.match(r'^(\s*)(#\s*)?(sub_file\s*=\s*)r?[\'"].*?[\'"](\s*(#.*)?)$', raw)
            if m_s:
                indent = m_s.group(1)
                expr = m_s.group(3)
                suffix = m_s.group(4) or ''
                want_commented = not bool(subtitle_path)
                comment_prefix = '# ' if want_commented else ''
                rhs = self._vpy_raw_string(subtitle_path or '')
                new_raw = f'{indent}{comment_prefix}{expr}{rhs}{suffix}'
                if new_raw != raw:
                    lines[idx] = new_raw + '\n'
                    changed = True
                mapping['sub_file'] = (raw, new_raw)
                continue

            m_t = re.match(
                r'^(\s*)(#\s*)?(res\s*=\s*core\.assrender\.TextSub\(\s*res\s*,\s*file\s*=\s*sub_file\s*\))(\s*(#.*)?)$',
                raw)
            if m_t:
                indent = m_t.group(1)
                expr = m_t.group(3)
                suffix = m_t.group(4) or ''
                want_commented = not bool(subtitle_path)
                comment_prefix = '# ' if want_commented else ''
                new_raw = f'{indent}{comment_prefix}{expr}{suffix}'
                if new_raw != raw:
                    lines[idx] = new_raw + '\n'
                    changed = True
                mapping['textsub'] = (raw, new_raw)
                continue

        if changed:
            with open(vpy_path, 'w', encoding='utf-8') as fp:
                fp.writelines(lines)
        return mapping

    def _create_temp_preview_vpy_from_default(self, video_path: str, subtitle_path: str) -> str:
        self.ensure_default_vpy_file()
        default_vpy = self.get_default_vpy_path()
        if not os.path.exists(default_vpy):
            return ''
        try:
            with open(default_vpy, 'r', encoding='utf-8') as fp:
                lines = fp.readlines()

            out: list[str] = []
            for line in lines:
                raw = line.rstrip('\r\n')

                if not raw.lstrip().startswith('#'):
                    m_a = re.match(r'^(\s*a\s*=\s*)r?[\'"].*?[\'"](\s*(#.*)?)$', raw)
                    if m_a:
                        out.append(f'{m_a.group(1)}{self._vpy_raw_string(video_path)}{m_a.group(2)}\n')
                        continue

                m_s = re.match(r'^(\s*)(#\s*)?(sub_file\s*=\s*)r?[\'"].*?[\'"](\s*(#.*)?)$', raw)
                if m_s:
                    indent = m_s.group(1)
                    expr = m_s.group(3)
                    suffix = m_s.group(4) or ''
                    comment = '' if subtitle_path else '# '
                    out.append(f'{indent}{comment}{expr}{self._vpy_raw_string(subtitle_path or "")}{suffix}\n')
                    continue

                m_t = re.match(
                    r'^(\s*)(#\s*)?(res\s*=\s*core\.assrender\.TextSub\(\s*res\s*,\s*file\s*=\s*sub_file\s*\))(\s*(#.*)?)$',
                    raw)
                if m_t:
                    indent = m_t.group(1)
                    expr = m_t.group(3)
                    suffix = m_t.group(4) or ''
                    comment = '' if subtitle_path else '# '
                    out.append(f'{indent}{comment}{expr}{suffix}\n')
                    continue

                if raw.strip() == 'dbed = mvf.LimitFilter(dbed, nr16, thr=0.55, elast=1.5, planes=[0, 1, 2])':
                    out.extend([
                        'try:\n',
                        '    dbed = mvf.LimitFilter(dbed, nr16, thr=0.55, elast=1.5, planes=[0, 1, 2])\n',
                        'except Exception:\n',
                        '    dbed = nr16\n',
                    ])
                    continue

                if raw.strip() == 'mergedY = mvf.LimitFilter(dbedY, aaedY, thr=1.0, elast=1.5)':
                    out.extend([
                        'try:\n',
                        '    mergedY = mvf.LimitFilter(dbedY, aaedY, thr=1.0, elast=1.5)\n',
                        'except Exception:\n',
                        '    mergedY = aaedY\n',
                    ])
                    continue

                out.append(line if line.endswith('\n') else line + '\n')

            fd, temp_vpy = tempfile.mkstemp(prefix='bluraysubtitle_preview_', suffix='.vpy')
            os.close(fd)
            with open(temp_vpy, 'w', encoding='utf-8') as fp:
                fp.writelines(out)
            return temp_vpy
        except Exception:
            print_exc_terminal()
            return ''

    def _create_temp_edit_vpy_from_default(self, video_path: str, subtitle_path: str) -> str:
        """Create a temporary editable copy of default vpy with row-specific a/sub_file values."""
        self.ensure_default_vpy_file()
        default_vpy = self.get_default_vpy_path()
        if not os.path.exists(default_vpy):
            return ''
        try:
            with open(default_vpy, 'r', encoding='utf-8') as fp:
                lines = fp.readlines()

            out: list[str] = []
            for line in lines:
                raw = line.rstrip('\r\n')

                m_a = re.match(r'^(\s*)(#\s*)?(a\s*=\s*)r?[\'"].*?[\'"](\s*(#.*)?)$', raw)
                if m_a:
                    indent = m_a.group(1)
                    expr = m_a.group(3)
                    suffix = m_a.group(4) or ''
                    out.append(f'{indent}{expr}{self._vpy_raw_string(video_path)}{suffix}\n')
                    continue

                m_s = re.match(r'^(\s*)(#\s*)?(sub_file\s*=\s*)r?[\'"].*?[\'"](\s*(#.*)?)$', raw)
                if m_s:
                    indent = m_s.group(1)
                    expr = m_s.group(3)
                    suffix = m_s.group(4) or ''
                    comment = '' if subtitle_path else '# '
                    out.append(f'{indent}{comment}{expr}{self._vpy_raw_string(subtitle_path or "")}{suffix}\n')
                    continue

                out.append(line if line.endswith('\n') else line + '\n')

            fd, temp_vpy = tempfile.mkstemp(prefix='bluraysubtitle_edit_', suffix='.vpy')
            os.close(fd)
            with open(temp_vpy, 'w', encoding='utf-8') as fp:
                fp.writelines(out)
            return temp_vpy
        except Exception:
            print_exc_terminal()
            return ''

    def _merge_temp_edit_back_to_default_vpy(self, temp_vpy: str):
        """Write edited temp script back into default vpy, preserving a=/sub_file= lines in default."""
        default_vpy = self.get_default_vpy_path()
        if not (temp_vpy and os.path.exists(temp_vpy) and os.path.exists(default_vpy)):
            return
        try:
            with open(default_vpy, 'r', encoding='utf-8') as fp:
                default_lines = fp.readlines()
            with open(temp_vpy, 'r', encoding='utf-8') as fp:
                temp_lines = fp.readlines()

            def _find_runtime_line(lines: list[str], key: str) -> Optional[str]:
                pat = re.compile(rf'^(\s*)(#\s*)?({re.escape(key)}\s*=\s*)r?[\'"].*?[\'"](\s*(#.*)?)$')
                for ln in lines:
                    raw = ln.rstrip('\r\n')
                    if pat.match(raw):
                        return ln if ln.endswith('\n') else ln + '\n'
                return None

            keep_a = _find_runtime_line(default_lines, 'a')
            keep_sub = _find_runtime_line(default_lines, 'sub_file')
            pat_a = re.compile(r'^(\s*)(#\s*)?(a\s*=\s*)r?[\'"].*?[\'"](\s*(#.*)?)$')
            pat_sub = re.compile(r'^(\s*)(#\s*)?(sub_file\s*=\s*)r?[\'"].*?[\'"](\s*(#.*)?)$')

            merged: list[str] = []
            for ln in temp_lines:
                raw = ln.rstrip('\r\n')
                if pat_a.match(raw) and keep_a is not None:
                    merged.append(keep_a)
                    continue
                if pat_sub.match(raw) and keep_sub is not None:
                    merged.append(keep_sub)
                    continue
                merged.append(ln if ln.endswith('\n') else ln + '\n')

            with open(default_vpy, 'w', encoding='utf-8') as fp:
                fp.writelines(merged)
        except Exception:
            print_exc_terminal()

    def _normalize_default_vpy_runtime_lines(self):
        """Ensure default vpy keeps empty runtime placeholders for a= and sub_file=."""
        default_vpy = self.get_default_vpy_path()
        if not os.path.exists(default_vpy):
            return
        try:
            with open(default_vpy, 'r', encoding='utf-8') as fp:
                lines = fp.readlines()
            changed = False
            out: list[str] = []
            for ln in lines:
                raw = ln.rstrip('\r\n')
                m_a = re.match(r'^(\s*)(#\s*)?(a\s*=\s*)r?[\'"].*?[\'"](\s*(#.*)?)$', raw)
                if m_a:
                    indent = m_a.group(1)
                    expr = m_a.group(3)
                    suffix = m_a.group(4) or ''
                    out.append(f'{indent}{expr}r""{suffix}\n')
                    changed = True
                    continue
                m_s = re.match(r'^(\s*)(#\s*)?(sub_file\s*=\s*)r?[\'"].*?[\'"](\s*(#.*)?)$', raw)
                if m_s:
                    indent = m_s.group(1)
                    expr = m_s.group(3)
                    suffix = m_s.group(4) or ''
                    out.append(f'{indent}# {expr}""{suffix}\n')
                    changed = True
                    continue
                out.append(ln if ln.endswith('\n') else ln + '\n')
            if changed:
                with open(default_vpy, 'w', encoding='utf-8') as fp:
                    fp.writelines(out)
        except Exception:
            print_exc_terminal()

    def _edit_vpy_with_default_sync(self, video_path: str, subtitle_path: str):
        """Open editable temp script and sync edits back to default vpy (except a=/sub_file=)."""
        temp_vpy = self._create_temp_edit_vpy_from_default(video_path=video_path or '',
                                                           subtitle_path=subtitle_path or '')
        if not temp_vpy:
            self.open_vpy_in_editor(self.get_default_vpy_path())
            return
        proc = self.open_vpy_in_vsedit(temp_vpy)
        if not proc:
            try:
                os.remove(temp_vpy)
            except Exception:
                pass
            self.open_vpy_in_editor(self.get_default_vpy_path())
            return
        if not hasattr(self, '_vsedit_edit_sessions'):
            self._vsedit_edit_sessions = {}
        self._vsedit_edit_sessions[proc] = temp_vpy

        def sync_and_cleanup(*_):
            try:
                sess_temp = self._vsedit_edit_sessions.pop(proc, '')
            except Exception:
                sess_temp = ''
            if sess_temp:
                self._merge_temp_edit_back_to_default_vpy(sess_temp)
                try:
                    os.remove(sess_temp)
                except Exception:
                    pass
            try:
                proc.deleteLater()
            except Exception:
                pass

        proc.finished.connect(sync_and_cleanup)
        proc.errorOccurred.connect(sync_and_cleanup)

    def _resolve_table2_row_edit_context(self, row_index: int) -> tuple[str, str]:
        """Return (video_path, subtitle_path) for table2 edit-vpy action."""
        if getattr(self, '_encode_input_mode', 'bdmv') == 'remux':
            video_path = self._get_remux_source_path_from_table2_row(row_index)
            subtitle_path = ''
            try:
                should_load_subtitle = bool(
                    getattr(self, 'sub_pack_hard_radio', None) and self.sub_pack_hard_radio.isChecked())
            except Exception:
                should_load_subtitle = False
            try:
                sub_col = ENCODE_REMUX_LABELS.index('sub_path')
                sub_item = self.table2.item(row_index, sub_col)
                subtitle_path = sub_item.text().strip() if should_load_subtitle and sub_item and sub_item.text().strip() else ''
            except Exception:
                subtitle_path = ''
            return video_path, subtitle_path

        try:
            bdmv_col = ENCODE_LABELS.index('bdmv_index')
            m2ts_col = ENCODE_LABELS.index('m2ts_file')
        except Exception:
            bdmv_col, m2ts_col = 2, 4
        bdmv_item = self.table2.item(row_index, bdmv_col)
        m2ts_item = self.table2.item(row_index, m2ts_col)
        sub_item = self.table2.item(row_index, 0)
        try:
            bdmv_index = int(bdmv_item.text().strip()) if bdmv_item and bdmv_item.text().strip() else -1
        except Exception:
            bdmv_index = -1
        m2ts_files = self._split_m2ts_files(m2ts_item.text() if m2ts_item else '')
        video_path = self._select_video_path(bdmv_index, m2ts_files)
        try:
            should_load_subtitle = bool(
                getattr(self, 'sub_pack_hard_radio', None) and self.sub_pack_hard_radio.isChecked())
        except Exception:
            should_load_subtitle = False
        subtitle_path = sub_item.text().strip() if should_load_subtitle and sub_item and sub_item.text().strip() else ''
        return video_path, subtitle_path

    def _resolve_table3_row_edit_context(self, row_index: int) -> tuple[str, str]:
        """Return (video_path, subtitle_path) for table3 edit-vpy action."""
        if getattr(self, '_encode_input_mode', 'bdmv') == 'remux':
            return self._get_remux_source_path_from_table3_row(row_index), ''
        try:
            bdmv_col = ENCODE_SP_LABELS.index('bdmv_index')
            m2ts_col = ENCODE_SP_LABELS.index('m2ts_file')
        except Exception:
            bdmv_col, m2ts_col = 0, 2
        bdmv_item = self.table3.item(row_index, bdmv_col)
        m2ts_item = self.table3.item(row_index, m2ts_col)
        try:
            bdmv_index = int(bdmv_item.text().strip()) if bdmv_item and bdmv_item.text().strip() else -1
        except Exception:
            bdmv_index = -1
        m2ts_files = self._split_m2ts_files(m2ts_item.text() if m2ts_item else '')
        return self._select_video_path(bdmv_index, m2ts_files), ''

    def _preview_script_for_row(self, vpy_path: str, video_path: str, subtitle_path: str):
        if not video_path:
            QMessageBox.information(self, "Prompt", "Cannot determine video file path")
            return

        vpy_path = (vpy_path or '').strip()
        default_vpy = self.get_default_vpy_path()
        if not vpy_path:
            vpy_path = default_vpy

        try:
            try:
                is_default = os.path.normcase(os.path.abspath(os.path.normpath(vpy_path))) == os.path.normcase(
                    os.path.abspath(os.path.normpath(default_vpy)))
            except Exception:
                is_default = False
            if is_default:
                self.ensure_default_vpy_file()
                temp_vpy = self._create_temp_preview_vpy_from_default(video_path=video_path,
                                                                      subtitle_path=subtitle_path or '')
                if not temp_vpy:
                    QMessageBox.warning(self, "Prompt", "Failed to generate preview script")
                    return
                proc = self.open_vpy_in_vsedit(temp_vpy)
                if not proc:
                    try:
                        os.remove(temp_vpy)
                    except Exception:
                        pass
                    return
                if not hasattr(self, '_vsedit_preview_sessions'):
                    self._vsedit_preview_sessions = {}
                self._vsedit_preview_sessions[proc] = temp_vpy

                def sync_and_cleanup(*_):
                    try:
                        sess_temp = self._vsedit_preview_sessions.pop(proc, '')
                    except Exception:
                        sess_temp = ''
                    if sess_temp:
                        # Preview temp scripts must never be merged back to default vpy.
                        # They contain preview-only edits (e.g. Trim) and compatibility wrappers.
                        try:
                            os.remove(sess_temp)
                        except Exception:
                            pass
                    try:
                        proc.deleteLater()
                    except Exception:
                        pass

                proc.finished.connect(sync_and_cleanup)
                proc.errorOccurred.connect(sync_and_cleanup)
            else:
                self._update_vpy_paths_in_file(vpy_path=vpy_path, video_path=video_path,
                                               subtitle_path=subtitle_path or '')
                self.open_vpy_in_vsedit(vpy_path)
        except Exception as e:
            QMessageBox.warning(self, "Prompt", f"Preview script failed: {e}")

    def on_edit_vpy_clicked(self):
        if self.get_selected_function_id() != 4:
            return
        sender = self.sender()
        if not sender:
            return
        try:
            row_index = self.table2.indexAt(sender.pos()).row()
        except Exception:
            row_index = -1
        if row_index < 0:
            return
        path = self.get_vpy_path_from_row(row_index)
        if not path:
            path = self.get_default_vpy_path()
            self.ensure_default_vpy_file()
        self.open_vpy_in_editor(path)

    def on_preview_script_clicked(self):
        if self.get_selected_function_id() != 4:
            return
        sender = self.sender()
        if not sender:
            return
        try:
            row_index = self.table2.indexAt(sender.pos()).row()
        except Exception:
            row_index = -1
        if row_index < 0:
            return

        if getattr(self, '_encode_input_mode', 'bdmv') == 'remux':
            video_path = self._get_remux_source_path_from_table2_row(row_index)
            should_load_subtitle = False
            try:
                should_load_subtitle = bool(
                    getattr(self, 'sub_pack_hard_radio', None) and self.sub_pack_hard_radio.isChecked())
            except Exception:
                should_load_subtitle = False
            subtitle_path = ''
            try:
                sub_col = ENCODE_REMUX_LABELS.index('sub_path')
                sub_item = self.table2.item(row_index, sub_col)
                subtitle_path = sub_item.text().strip() if should_load_subtitle and sub_item and sub_item.text().strip() else ''
            except Exception:
                subtitle_path = ''
            vpy_path = self.get_vpy_path_from_row(row_index)
            self._preview_script_for_row(vpy_path=vpy_path, video_path=video_path, subtitle_path=subtitle_path)
            return

        try:
            bdmv_col = ENCODE_LABELS.index('bdmv_index')
            m2ts_col = ENCODE_LABELS.index('m2ts_file')
        except Exception:
            bdmv_col, m2ts_col = 2, 4

        bdmv_item = self.table2.item(row_index, bdmv_col)
        m2ts_item = self.table2.item(row_index, m2ts_col)
        sub_item = self.table2.item(row_index, 0)

        try:
            bdmv_index = int(bdmv_item.text().strip()) if bdmv_item and bdmv_item.text().strip() else -1
        except Exception:
            bdmv_index = -1

        m2ts_files = self._split_m2ts_files(m2ts_item.text() if m2ts_item else '')
        video_path = self._select_video_path(bdmv_index, m2ts_files)
        should_load_subtitle = False
        try:
            should_load_subtitle = bool(
                getattr(self, 'sub_pack_hard_radio', None) and self.sub_pack_hard_radio.isChecked())
        except Exception:
            should_load_subtitle = False
        subtitle_path = sub_item.text().strip() if should_load_subtitle and sub_item and sub_item.text().strip() else ''

        vpy_path = self.get_vpy_path_from_row(row_index)
        self._preview_script_for_row(vpy_path=vpy_path, video_path=video_path, subtitle_path=subtitle_path)

    def get_sp_vpy_path_from_row(self, row_index: int) -> str:
        if self.get_selected_function_id() != 4:
            return ''
        labels = ENCODE_REMUX_SP_LABELS if getattr(self, '_encode_input_mode', 'bdmv') == 'remux' else ENCODE_SP_LABELS
        vpy_col = labels.index('vpy_path')
        w = self.table3.cellWidget(row_index, vpy_col)
        if w:
            line_edit = w.findChild(QLineEdit)
            if line_edit:
                return line_edit.text().strip()
        item = self.table3.item(row_index, vpy_col)
        return item.text().strip() if item else ''

    def on_edit_sp_vpy_clicked(self):
        if self.get_selected_function_id() != 4:
            return
        sender = self.sender()
        if not sender:
            return
        try:
            row_index = self.table3.indexAt(sender.pos()).row()
        except Exception:
            row_index = -1
        if row_index < 0:
            return
        path = self.get_sp_vpy_path_from_row(row_index)
        if not path:
            path = self.get_default_vpy_path()
            self.ensure_default_vpy_file()
        self.open_vpy_in_editor(path)

    def on_preview_sp_scripts_clicked(self):
        if self.get_selected_function_id() != 4:
            return
        sender = self.sender()
        if not sender:
            return
        try:
            row_index = self.table3.indexAt(sender.pos()).row()
        except Exception:
            row_index = -1
        if row_index < 0:
            return

        if getattr(self, '_encode_input_mode', 'bdmv') == 'remux':
            video_path = self._get_remux_source_path_from_table3_row(row_index)
            vpy_path = self.get_sp_vpy_path_from_row(row_index)
            self._preview_script_for_row(vpy_path=vpy_path, video_path=video_path, subtitle_path='')
            return

        try:
            bdmv_col = ENCODE_SP_LABELS.index('bdmv_index')
            m2ts_col = ENCODE_SP_LABELS.index('m2ts_file')
        except Exception:
            bdmv_col, m2ts_col = 0, 2

        bdmv_item = self.table3.item(row_index, bdmv_col)
        m2ts_item = self.table3.item(row_index, m2ts_col)
        try:
            bdmv_index = int(bdmv_item.text().strip()) if bdmv_item and bdmv_item.text().strip() else -1
        except Exception:
            bdmv_index = -1

        m2ts_files = self._split_m2ts_files(m2ts_item.text() if m2ts_item else '')
        video_path = self._select_video_path(bdmv_index, m2ts_files)
        subtitle_path = ''

        vpy_path = self.get_sp_vpy_path_from_row(row_index)
        self._preview_script_for_row(vpy_path=vpy_path, video_path=video_path, subtitle_path=subtitle_path)
